# used to configure job submission at the global/rule level

__default__:
  job-name: "{rule}"
  partition: short
  time: 10 # minutes
  nodes: 1
  ntasks: 1
  ntasks-per-node: 1
  mem: 1gb
  output: "log/{rule}-%j.out"
  error: "log/{rule}-%j.err"

MakeGiggleNormal:
  time: 720 # minutes
  nodes: 1
  ntasks: 1
  mem: 32gb

MakeGiggleTumor:
  time: 720 # minutes
  nodes: 1
  ntasks: 1
  mem: 32gb
