# used to configure job submission at the global/rule level

__default__:
  partition: short
  time: 00:01:00
  nodes: 1
  ntasks-per-node: 1

GetTumorNormalBedLists :
  job-name: GetTumorNormalBedLists
  partition: short
  time: 00:01:00
  nodes: 1
  ntasks-per-node: 1
  mem: 1gb
  output: log/GetTumornormalBedLists-%j.out
  error: log/GetTumornormalBedLists-%j.err

MakeGiggleNormal:
  job-name: MakeGiggleNormal
  partition: short
  time: 00:25:00
  nodes: 1
  ntasks-per-node: 1
  mem: 32gb
  output: log/MakeGiggleNormal-%j.out
  error: log/MakeGiggleNormal-%j.err
